= Documentation technique Esup-Stage
:author: Université Lorraine
:imagesdir: ../images/


== Vocabulaire du domaine

Stage:: #TODO#
Convention (lié à un centre de gestion via les critères):: #TODO#
PDF Convention:: #TODO#
Centre de gestion:: #TODO#
Validation administrative:: #TODO#
Validation pédagogique:: #TODO#
Signature de la Convention:: #TODO#
Avenant:: #TODO#
PDF Avenant:: #TODO#
Évaluation de stage:: #TODO#
Modèle de convention:: #TODO#
Modèle d’avenant:: #TODO#
Modèle de mail:: #TODO#
Etablissement d’accueil:: #TODO#
Etape : VET:: #TODO#
UFR:: #TODO#
Critères de gestion:: #TODO#
Type de convention:: #TODO#

== Décisions Stratégique

* Un stage a toujours une convention

== Flux
=== Flux Entrant

==== Application de signature électronique

.Messages
** PDF *signés*
*** Convention
*** Avenant

.Systèmes (1 seul au choix, configuration)
* Esup-signature ou _autre_
** API serveur et client dans une séquence
CAUTION: Lien vers doc(s) à trouver _svp_
* Docaposte
** [JAX-RS client, WSDL]


==== Esup-siscol

[plantuml]
....
left to right direction
card e_ins as "Étudiant inscrit\n(Apogée)"
card esup_siscol as "Esup-siscol"
card esup_stage as "Esup-Stage"
e_ins <-0)- esup_siscol: "WS Apogée"
esup_siscol <-0)- esup_stage
....

//'@startuml
//'card e_ins as "Étudiant inscrit (Apogée)"
//'
//'interface ws_apo as "WS Apogée"
//'
//'card siscol as Esup-siscol
//'
//'e_ins -> ws_apo
//'
//'' Etudiant inscrit (Apogée) ← WS Apogée← Esup-siscol ← Esup-Stage
//'@enduml


=== Flux Sortant

==== Application de signature (_c.f._ flux entrant)

** PDF *à signer*
*** Convention
*** Avenant

.Systèmes (1 seul au choix, configuration)
* Esup-signature ou _autre_
** API serveur et client dans une séquence
CAUTION: Lien vers doc(s) à trouver _svp_
* Docaposte
** [JAX-RS client, WSDL]

