= Documentation technique Esup-Stage
:author: Université Lorraine
:imagesdir: ../images/
:reftext: Documentation technique
:navtitle: Documentation technique

****
ESUP-Stage est l'application qui permet aux étudiants de créer et faire signer
leur(s) convention(s) de stage. Développée dans une technologie moderne, cette
solution est prévue pour s'interconnecter avec l'annuaire LDAP des
établissements ainsi qu'Apogée dans un premier temps. Des travaux sont en cours
avec les équipes PC-Scol pour assurer une compatibilité avec Pégase.

* Interface utilisateur modernisée,
* facilité de configuration de l'application selon les besoins de chaque
établissement,
* gestion fine des droits d'utilisateur,
* matérialisation des étapes de création d'une convention ergonomique.
* Par ailleurs, le périmètre d'utilisation de l'application s'élargit en
permettant son utilisation par les INSPÉ avec notamment la possibilité
de créer des conventions de stage en masse.
* Ouverture vers la dématérialisation des signatures
* La dématérialisation du processus de création et validation des conventions est au cœur des préoccupations du groupe de travail œuvrant pour le développement et l'évolution de ESUP-Stage. Aussi arrivera prochainement la possibilité d'interfacer via un webservice la solution ESUP-Signature ou toute solution commerciale compatible.
****

== xref:vocabulaire.adoc[]
== xref:decisions.adoc[]
== xref:flux.adoc[]
== xref:archi-tech.adoc[]
