---

###################################################################
### CHECK PARAMs                                             ######
###################################################################
- name: Test.params.subtasks
  fail: 
    msg: "webapp-redeploy => missing parameters (tomcatid,webapp,delai)"
  when: (tomcatid is not defined) or (webapp is not defined) or (delai is not defined)


# stopper le tomcat
- name: tomcat.stop
  service: 
    name: {{ tomcatid }}
    state: stopped
- name: tomcat.stop.wait
  pause: 
    seconds: 5


# copier le war et decompresser la webapp
- name: tomcat.webapp.delete-war
  file: 
    path: "/srv/{{ tomcatid }}/{{ webapp }}.war"
    state: absent
- name: tomcat.webapp.delete-dir
  file: 
    path: "/srv/{{ tomcatid }}/{{ webapp }}"
    state: absent
- name: tomcat.webapp.create-dir
  file: 
    path: "/srv/{{ tomcatid }}/{{ webapp }}"
    state: directory
    owner: tomcat
    group: tomcat
    mode: 0755
- name: tomcat.webapp.decompress-war
  unarchive: 
    remote_src: yes
    src: "/usr/local/catalina-war-repo/{{ tomcatid }}_{{ webapp }}.war"
    dest: "/srv/{{ tomcatid }}/{{ webapp }}"
    owner: tomcat
    group: tomcat
- name: tomcat.webapp.publicated-war
  copy: 
    remote_src: yes
    src: "/usr/local/catalina-war-repo/{{ tomcatid }}_{{ webapp }}.war"
    dest: "/usr/local/catalina-war-repo/{{ tomcatid }}_{{ webapp }}.war.published"
    owner: tomcat
    group: tomcat
    mode: 0644


# SPECIFIC
### nothing todo


# demarrer le tomcat
- name: tomcat.started
  service: 
    name: {{ tomcatid }}
    state: started
- name: tomcat.stop.wait
  pause: 
    seconds: {{ delai }}
