---
kind: pipeline
type: docker
name: CI

steps:
- name: build-test
  user: root
  image: maven:3-openjdk-11-slim
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B

- name: Publish
  image: plugins/docker
  settings:
    username: admin
    password: esupstage
    repo: esupstage-registry.parisnanterre.fr/drone/esupstage
    registry: esupstage-registry.parisnanterre.fr
    dockerfile: ./Dockerfile
    tags:
      - ${DRONE_COMMIT_BRANCH}
      - latest

---
kind: pipeline
type: exec
name: CD

platform:
  os: linux
  arch: amd64
  
  - name: compose
    commands:
      - cd /opt/docker-compose-projects/drone/esup-stage
      - touch compose.txt
      
trigger:
  branch:
  - dev
