kind: pipeline
name: default

steps:
- name: test
  image: maven:3-openjdk-11-slim
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B

- name: Publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: esupstage-registry.parisnanterre.fr/drone/esupstage
    registry: esupstage-registry.parisnanterre.fr
    dockerfile: ./Dockerfile
    auto_tag: true
    
trigger:
  branch:
  - dev
