services:
  esup-stage:
    image: ${IMAGE_REPO}${IMAGE_NAME}:${IMAGE_TAG}
    container_name: ${IMAGE_NAME}
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - data:${DATA_PATH}
volumes:
  data:
    driver: local