= esup-stage

// URIs:
:uri-org: https://github.com/EsupPortail
:uri-repo: {uri-org}/esup-stage
:uri-build-status: {uri-repo}/workflows/Dev/badge.svg
:uri-sonarcloud: https://sonarcloud.io
:uri-sonarcloud-badge: {uri-sonarcloud}/api/project_badges/measure?project=EsupPortail_esup-stage&metric=alert_status
:uri-sonarcloud-project: {uri-sonarcloud}/dashboard?id=EsupPortail_esup-stage
:uri-fakesmpt: http://nilhcem.com/FakeSMTP
:uri-asciidoctor: https://asciidoctor.org
:uri-asciidoctor-syntax: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference
:uri-atom: https://atom.io
:uri-atom-packages: {uri-atom}/packages
:uri-atom-packages-asciidoc-assistant: {uri-atom-packages}/asciidoc-assistant

image:{uri-build-status}[Status, link={uri-repo}]
image:{uri-sonarcloud-badge}[Sonarcloud, link={uri-sonarcloud-project}]

== Prerequisite

* Tomcat 9
* Java 11
* Maven 3

== Tools

=== Swagger-ui 3.0.0

Swagger-ui is used to display the application API. +
We can access it from http://localhost:8080/swagger-ui/[/swagger-ui/].

=== AsciiDoctor

We use the Asciidoc {uri-asciidoctor-syntax}[syntax] to write the documentation. +
On {uri-atom}[Atom], we can install the package {uri-atom-packages-asciidoc-assistant}[asciidoc-assistant] to help us write the documentation.

=== FakeSMTP

To test the sending of email in development, we can use {uri-fakesmpt}[FakeSMTP].

.To launch fakeSMTP from the console
----
java -jar fakeSMTP-2.0.jar -o ./fakeSMTP-output
----

== System specific configuration

To overwrite the configuration for a specific system, we can simply add the following property `spring.config.additional-location` to the launch configuration. This property take a path to a directory containing any number of `application(-*).yml` files in which we can overwrite parameters.

.example of property launch configuration
[source,properties]
----
spring.config.additional-location=C:/development/config/ESUP/Stage/
----

.example of `application.yml` content
[source,yaml]
----
---
spring:
  profiles:
    include: # <1>
    - embedded-ldap
    - mariadb
...
---
spring:
  profiles: mariadb # <2>
  datasource: # <3>
    url: jdbc:mariadb://localhost:3306/esupstage
    username: esupstage
    password: esupstage
...
----
<1> Configure the list of profiles to be used.
<2> Overwrite the profiles which need to be configured for your specific use case.
<3> Overwrite here specific values which we don't want to push on the Git repository.

== Liquibase initialization

We used the following https://docs.liquibase.com/workflows/liquibase-community/existing-project.html[guide] to generate the first Liquibase script and ensure that the application could run.

.Generate the base Liquibase script
----
liquibase --changeLogFile=db.changelog-base.yaml  --url=jdbc:mariadb://localhost:3306/<databaseName> --username=<userName> --password=<password> --classpath="<pathToMavenRepo>\org\mariadb\jdbc\mariadb-java-client\2.7.0\mariadb-java-client-2.7.0.jar" generateChangeLog
----

.Generate the Liquibase's specific tables
----
liquibase --changeLogFile=db.changelog-base.yaml  --url=jdbc:mariadb://localhost:3306/<databaseName> --username=<userName> --password=<password> --classpath="<pathToMavenRepo>\org\mariadb\jdbc\mariadb-java-client\2.7.0\mariadb-java-client-2.7.0.jar" changelogSyncSQL
----

.Fill these Liquibase's specific tables
----
liquibase --changeLogFile=db.changelog-base.yaml  --url=jdbc:mariadb://localhost:3306/<databaseName> --username=<userName> --password=<password> --classpath="<pathToMavenRepo>\org\mariadb\jdbc\mariadb-java-client\2.7.0\mariadb-java-client-2.7.0.jar" changelogSync
----

.Update the `filename` column to match the expected value from running the application.
[source,sql]
----
update `databasechangelog` d set d.`filename` = 'classpath:/db/changelog/db.changelog-base.yaml' where d.`filename` = 'db.changelog-base.yaml'̦;
----
