
= ESUP Stage

ESUP STAGE est la refonte de l'application PStage. L'application a été complètement réécrite pour reprendre et améliorer les grandes et fonctionnalités : produire une convention de stage et ses avenants dans le cadre d'un processus de validation adapté.

== https://esupportail.github.io/esup-stage/[→ Documentation technique Esup-Stage]

// ifndef::env-github[]
// include::src/docs/modules/ROOT/pages/ESUP-STAGE.adoc[tag=compilation]
// endif::[]
// ifdef::env-github[]
// == link:src/docs/modules/ROOT/pages/ESUP-STAGE.adoc#compilation[→ Compilation]
// endif::[]

== Prérequis

.Les xref:src\docs\modules\ROOT\pages\Prerequis.adoc[prérequis] sont les suivants sur votre serveur :
* Git
* Java OpenJdk 21
* Apache Maven
* Installation Mariadb
* Installation du projet Esup-SIscol (sur le même serveur ou sur un serveur dédié)

[#la-base-de-donnees]
== La base de données

=== Création de la base et de l'utilisateur

[source,SQL]
----
CREATE DATABASE estage;
CREATE USER 'esupstage_user'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON estage.* TO 'esupstage_user'@'%';
FLUSH PRIVILEGES;
----

=== Import de la base pStage et passage du patch

TIP: Si vous n'avez pas de base pStage a reprendre, cette partie est inutile

Pour importer votre base pStage d'une installation en production, vous devez réaliser un dump, ici le fichier : +
`mysql-pstage-2022-01-25-16h00.sql.gz`

CAUTION: Votre dump ne doit pas comporter de `CREATE DATABASE` ou `USE DATABASE`

Les commandes suivantes permettent d'importer votre dump (pStage) dans votre base estage (ESUP STAGE) :

[source,shell]
----
zcat /opt/estage/mysql-pstage-2022-01-25-16h00.sql.gz | mysql -u esupstage_user -p estage
cat /opt/estage/src/main/resources/db/changelog/init-changelog.sql | mysql -u esupstage_user -p estage
----

Par la suite, dans le application.properties, devrez renseigner le paramètre suivant :

[source,properties]
----
appli.datasource.context=legacy
----

=== Base données sans import de pStage

Si vous n'avez pas de base pStage à importer, vous devrez renseigner le paramètre suivant dans le application.properties pour créer une nouvelle base de données vide :

[source,properties]
----
appli.datasource.context=baseline
----

== Clonage du projet

[source,shell]
----
cd /opt
git clone https://github.com/EsupPortail/esup-stage.git
----

[source,shell]
----
mkdir -p /etc/estage
cp /opt/esup-stage/application-example.properties /etc/estage/application.properties
----



== Modification du fichier de configuration

=== Modifications apportées au fichier de configuration pour la version 3

* *Renommage* du fichier de config `estage.properties` en `application.properties`
** *__A placer à la racine du projet__*, il sera interprété automatiquement par Spring Boot
* `appli.tokens` : précédement `appli.public.tokens`, *renommé* pour cause technique (le mot clé `public` étant réservé)
* Pour *éviter les redondances* de valeurs, les champs suivants ont été modifiés :
** `cas.url.login` : devient *optionnel* et ne peut maintenant contenir que le path de connexion :  `/login` (saisie de l'url entière toujours possible)
** `cas.url.logout` : devient *optionnel* et ne peut maintenant contenir que le path de déconnexion :  `/logout` (saisie de l'url entière toujours possible)
** `appli.localapi` : devient *optionnel*, sera utilisé en remplacement de `appli.url` lors des appels api sur elle-même (cas d'un reverse proxy par exemple)
* *Ajout d'une nouvelle propriété*
** Ajout de la propriété `appli.datasource.context` à partir de la *version 3.1.0*, qui permet de choisir entre la création d'une nouvelle base de données vide ou la reprise d'une base de données existante (comme avant l'introduction de ce paramètre). Cette propriété doit *obligatoirement* être renseignée.


[source,properties]
./etc/estage/application.properties
----
# URLs pour l'authentication CAS
cas.url.service=https://auth.domain.fr/cas
# Url login/logout CAS optionnel, par défaut /login et /logout
# cas.url.login=/login
# cas.url.logout=/logout
# Parametre permettant de gerer le retour CAS au format XML (au lieu de JSON par defaut)
# cas.response_type=xml

# Config Base de donnees
appli.datasource.url=jdbc:mariadb://db-host:3306/estage
appli.datasource.username=estage
appli.datasource.password=xxx
appli.datasource.driver=org.mariadb.jdbc.Driver
# =============================== IMPORTANT ==================================
# Contexte de la base de donnees
# * Pour utiliser une nouvelle base de donnees, utilser le contexte "baseline"
# * Pour utiliser une base de donnees existante, utiliser le contexte "legacy"
# Une fois le contexte choisi, il ne faut pas le changer
# ============================================================================
appli.datasource.context=baseline

# url de l'application pour les mails
appli.url=http://localhost:8080

# Logins des administrateurs techniques, separes par des ; (exemple : admin1;admin2;admin3)
appli.admin_technique=xxx;yyy

# Config esup-siscol - Web Services referentiel
referentiel.ws.login=root
referentiel.ws.password=xxx
# Url du service LDAP
referentiel.ws.ldap_url=https://referentiel.domain.fr/ldap
# Url du service Apogee
referentiel.ws.apogee_url=https://referentiel.domain.fr/apogee

# Config SMTP
appli.mailer.protocol=smtp
appli.mailer.host=smtp.univ.fr
appli.mailer.ssl.enable=true
#appli.mailer.starttls.enable=false
#appli.mailer.starttls.required=false
appli.mailer.port=25
appli.mailer.auth=true
appli.mailer.username=username@domain.com
appli.mailer.password=xxx
appli.mailer.from=from@domain.com
# Pour le developpement : disable_delivery=false, delivery_address=null
appli.mailer.disable_delivery=false
appli.mailer.delivery_address=

# Chemin vers le dossier contenant les fichiers (logos, conventions signées,...)
# Avec DOCKER : se référer à la variable d'environnement DATA_PATH présente dans example.env
appli.data_dir=target/data

# Config Docaposte
docaposte.uri=https://demo-parapheur.dfast.fr/parapheur-soap/soap/v1/Documents
docaposte.siren=0123456789
docaposte.keystore.path=/data/certificat.p12
docaposte.keystore.password=xxx
docaposte.truststore.path=/data/ProductionFAST.jks
docaposte.truststore.password=xxx

# Tokens d'acces d'esup-stage permettant d'autoriser les webhook a acceder aux api /public/api d'esup-stage separes par des ; (exemple : token1;token2;token3)
appli.tokens=xxxx

# Config webhook de signature
webhook.signature.uri=http://localhost:8080/webhook/esup-signature
# Token d'acces
webhook.signature.token=yyyyy

# Config esup-signature
esupsignature.uri=http://localhost:8880/ws
esupsignature.circuit=123

## Parametrage de l'api sirene ##
# ne pas remplir pour desactiver l'api sirene
sirene.url=https://api.insee.fr/api-sirene/3.11
sirene.token=zzzz
sirene.nombre_minimum_resultats=3

#############################################
# JWT CONFIGURATION
#############################################

# Secret utilisé pour signer les JWT (algorithmes HS256 / HS512)
# DOIT être remplacé par une valeur sécurisée
# Minimum recommandé : 32 caractères aléatoires
# Exemple pour générer une clé : `openssl rand -base64 64`
appli.jwt_secret=__DEFINE_A_RANDOM_SECRET__

# Durée de validité d?un token JWT (en jours)
appli.nb_jours_valide_token=60


# Configuation des urls du footer de l'application (facultatif)
# Les valeurs par défaut sont celles d'esup-portail, mais elles peuvent être personnalisées pour chaque instance d'esup-stage
# Si une url n'est pas renseignée, le lien correspondant ne sera pas affiché dans le footer de l'application
appli.footer.github=https://github.com/EsupPortail/esup-stage
appli.footer.site=https://www.esup-portail.org/
appli.footer.support=https://assistance.univ-exemple.fr/
appli.footer.wiki=https://wiki.esup-portail.org/display/ESUPSTAGE/ESUP-Stage
----

NOTE: il faut que l'utilisateur faisant tourner votre *Tomcat puisse avoir les droits en écriture sur le répertoire data_esup_stage*

== Stockage de fichiers

* La variable `appli.data_dir` dans `application.properties` définie le répertoire de stockage des fichiers.
L'application *se charge de créer les répertoires* suivants : si `appli.data_dir=/volume/data` on aura :

----
/volume
    |_/data
        |_/centregestion
            |_/consigne-documents
            |_/logos
        |_/images
        |_/signatures
----

== link:src/docs/modules/ROOT/pages/signature.adoc[→ Signature électronique (optionnel)]

== Génération de l'application (.war)

WARNING: Si vous aviez déjà une version antérieure d'ESUP STAGE et que vous en installer une nouvelle, il est fortement recommandé de supprimer de supprimer le package-lock.json et les node_modules dans le dossier frontend avant de lancer la compilation.

* Build du war de l'application : esup-stage-3.x.x.war

[,console]

----
mvn clean package
----

* Pour une exécution en local de l'application

A la racine de l'application, *renommer* et *complèter* le fichier `application-example.properties` en `application.properties`, puis exécuter :

[,console]
----
mvn clean package cargo:run
----


== Déploiement / Lancement de l'application

Après la compilation, le chemin complet du fichier de déploiement est le suivant : `/opt/estage/target/ROOT.war`

== Exécution de l'application avec __Docker__


* Créer un fichier `.env` basé sur le fichier `example.env`
** Adapter les paramètres, notamment `DATA_PATH` qui doit correspondre au volume de stockage des fichiers
* Lancer la commande `docker-compose up` depuis la racine du projet
** docker-compose utilisera les fichiers de configuration `.env` et `application.properties` présent à la racine du projet
** L'exécution récupère une image docker publique de l'application disponible sur `https://harbor.esup-portail.org/`

TIP: Pour utiliser un tag particulier, consultez le dernier tag à utiliser https://github.com/EsupPortail/esup-stage/actions/workflows/docker-image.yml[ici]


* L'application est alors accessible sur : `http://localhost:8080/`

== Exécution de l'application avec __Tomcat__

NOTE: Cette documentation ne va pas décrire l'installation d'un Tomcat.
ESUP STAGE a été déployé et testé sur une version TOMCAT 10

TIP: Vous pouvez télécharger tomcat ici : https://tomcat.apache.org/download-10.cgi

Nous considérons par exemple le chemin du répertoire tomcat ainsi : `/opt/tomcat-esup-stage`

//wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.41/bin/apache-tomcat-10.1.41.tar.gz

//tar xzf apache-tomcat-10.1.41.tar.gz

//ln -sfn apache-tomcat-10.1.41.tar.gz tomcat-esup-stage



=== Paramétré __Tomcat__

Pour exécuter l'application avec Tomcat, il faut lui renseigné les paramètre de jvm nécessaire. Pour ce faire, créer un fichier setenv.sh :

[source,shell]
----
nano /opt/tomcat-esup-stage/bin/setenv.sh
----

Renseigné les paramètres suivant dans le fichier, les deux premiers étant les options de jvm et la troisième le répertoire où trouver l'application.properties.

[source,shell]
----
export JAVA_OPTS="-Xms1024m -Xmx1024m -Dspring.config.additional-location=/etc/estage/application.properties"
----

Cela permet d'éviter de devoir penser a remettre les options a chaque fois qu'on relance Tomcat.

TIP: Vous pouvez placer le .properties dans le répertoire de votre choix, il suffit de le renseigner dans Dspring.config.location

=== Exécution avec __Tomcat__

Supprimer (ou déplacer une sauvegarde) votre répertoire `/opt/tomcat-esup-stage/webapp/ROOT` avant le déploiement

Copier directement votre fichier `/opt/estage/target/ROOT.war` dans votre répertoire *`webapp` de tomcat*

[source,shell]
----
cp /opt/esup-stage/target/esup-stage-3.0.0.4.war /opt/tomcat-esup-stage/webapps/
----

On arrête le tomcat avant et on le redémarre ensuite

[source,shell]
----
/opt/tomcat-esup-stage/bin/shutdown.sh
----

Démarrage :

[source,shell]
----
/opt/tomcat-esup-stage/bin/startup.sh
----

Bravo, l'installation est terminée ! Vous pouvez y accéder sur http://localhost:8080

Lancement direct du `war` (ne pas utiliser : en cours de debug) `java -jar /opt/estage/target/ROOT.war`

Dans le cas de l'utilisation d'un proxy (apache proxypass par exemple) il est conseillé d'utiliser le protocole AJP.

[source,apacheconf]
.Exemple de configuration Apache :
----
<VirtualHost *:80>
    ServerAdmin admin@monuniv.fr
    ServerName esup-stage.monuniv.fr
    DefaultType text/html
    ProxyRequests off
    ProxyPreserveHost On
    ProxyPass / http://localhost:8080/
    ProxyPassReverse / http://localhost:8080/
</VirtualHost>
----

TIP: Le fichier application.properties peut être positionné à la racine du tomcat et renseigné dans la commande d'exécution avec `-Dspring.config.location=$HOMEDIR/application.properties`

== Exécution local en mode pour __dév__ avec l'__hot reload d'angular__

* Créer un fichier `application.properties` basé sur le fichier `application-example.properties`
* Lancer le serveur avec une commande maven `clean package cargo:run`
** L'application est alors accessible sur : `http://localhost:8080/`

* Pour lancer le frontend avec le mode dev d'angular, en *hot reload* (rechargement à chaud en cas de modification du code) :
 ** Exécuter la commande `ng serve --host localhost --proxy-config src/proxy.conf.json` au niveau du dossier frontend (node et npm devront être installés)
* Se rendre sur l'application à l'adresse `http://localhost:8080/` pour se connecter une première fois
* Puis se rendre sur `http://localhost:4200`
* Pour se déconnecter, aller sur `http://localhost:4200/logout`
