version: '3.4'
services:
  mariadb:
    network_mode: bridge
    tty: true
    container_name: mariadb
    # Image: https://hub.docker.com/_/mariadb
    image: mariadb:${MARIADB_VERSION:-10.4}
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-pwd2change}
      # Autres variables d'environement possibles :
      # MYSQL_DATABASE
      # MYSQL_USER
      # MYSQL_PASSWORD
      # MYSQL_ALLOW_EMPTY_PASSWORD: yes
      # ...
    volumes:
      - data:/var/lib/mysql
      - ./conf:/opt/scripts/
volumes:
  data:
    name: data_mariadb