export enum AppFonction {
  PARAM_GLOBAL = 'PARAM_GLOBAL',
  PARAM_CENTRE = 'PARAM_CENTRE',
  CONVENTION = 'CONVENTION',
  AVENANT = 'AVENANT',
  ORGA_ACC = 'ORGA_ACC',
  NOMENCLATURE = 'NOMENCLATURE',
  CREATION_EN_MASSE_CONVENTION = 'CREATION_EN_MASSE_CONVENTION',
  SERVICE_CONTACT_ACC = 'SERVICE_CONTACT_ACC',
}
