INSERT INTO Contenu (codeContenu, libelle, texte, loginCreation, dateCreation) VALUES
('TITRE_APPLICATION', TRUE, 'Gestion des conventions et des offres de Stage', 'liquibase', NOW()),
('TEXTE_ACCUEIL', FALSE, 'Bienvenue sur votre application de gestion des conventions de Stage.', 'liquibase', NOW()),
('BOUTON_VALIDER', TRUE, 'Valider', 'liquibase', NOW()),
('BOUTON_ANNULER', TRUE, 'Annuler', 'liquibase', NOW()),
('TEXTE_LIMITE_RENUMERATION', FALSE, 'La limite basse de rémunération à ne pas dépasser est $limite', 'liquibase', NOW()),
('NOMENCLATURE_LIBELLE_EXISTANT', TRUE, 'Libellé déjà existant', 'liquibase', NOW()),
('NOMENCLATURE_CODE_EXISTANT', TRUE, 'Code déjà existant', 'liquibase', NOW()),
('CONVENTION_DEJA_VALIDEE_ADMIN', TRUE, 'Convention déjà validée administrativement', 'liquibase', NOW()),
('TEXTE_RECAPITULATIF', TRUE, 'Conformément au Règlement (UE) 2016/679 du Parlement européen et du Conseil du 27 avril 2016 relatif à la protection des personnes physiques à l''égard du traitement des données à caractère personnel et à la libre circulation de ces données (ci-après "RGPD"), entré en vigueur le 25 mai 2018, et à la loi Informatique et Libertés du 6 janvier 1978 modifiée, les données personnelles recueillies feront l''objet d''un traitement uniquement pour permettre la gestion de la demande de convention de stage. Vous disposez d''un droit d''accès, de rectification et d''effacement de vos données personnelles, lesquels droits peuvent être exercés auprès du délégué à la protection des données de l''Université XXXXXX, à l''adresse  DPO Université Paris-Dauphine - Place de XXXXXXXXXX ou à l''adresse courriel suivante  dpo@XXXXX.fr.', 'liquibase', NOW()),
('TEXTE_ALERTE_FICHE',FALSE,'<p>Les données sur la convention de stage et les questionnaires faisant l’objet d’un traitement informatique, la loi du 6 janvier 1978 relative à l’informatique, aux fichiers, et aux libertés, donne aux individus impliqués un droit d’accès et de rectification sur les données les concernant. Pour ce faire, la personne peut s’adresser au service gestionnaire des stages de l’université.</p><p>Concernant le questionnaire d’évaluation de l’étudiant en particulier, il est rappelé que le document ne doit pas être pris en compte dans l’évaluation de l’étudiant ou dans l''obtention de son diplôme (article L. 612-14. de la Loi n° 2013-660 du 22 juillet 2013 relative à l''enseignement supérieur et à la recherche).</p><p>Soyez également alerté que les nouvelles informations personnelles demandées via les fiches d''évaluation doivent être portées à la connaissance de votre correspondant informatique et liberté.</p>','liquibase',NOW()),
('ALERTE_SIGNATURE',TRUE,'Attention, l''envoi pour signature électronique est définitive, vous ne pourrez plus modifier la convention. Souhaitez-vous continuer ?','liquibase',NOW());