INSERT INTO Devise (idDevise, libelleDevise, temEnServDevise) VALUES
(1, 'euros', 'O'),
(2, 'franc suisse', 'O'),
(3, 'USD', 'O'),
(4, 'CHF', 'O'),
(5, 'dollar', 'O'),
(6, 'dirhams', 'O'),
(7, 'DH', 'O'),
(8, 'CAD', 'O'),
(9, 'zloty', 'O'),
(10, 'livres', 'O'),
(11, 'Livre Sterling ', 'O'),
(12, 'francs suisse', 'O'),
(13, 'Francs dj', 'O'),
(14, 'DOLLAR CAN', 'O'),
(15, 'RMB', 'O'),
(16, 'sek', 'O'),
(17, 'livres sterling', 'O'),
(18, 'DKK-Couronne Danoise', 'O'),
(19, 'rupiah', 'O'),
(20, 'CFA', 'O'),
(21, 'couronne tchèque', 'O'),
(22, 'dollars', 'O'),
(23, 'XPF', 'O'),
(24, 'dollars canadiens', 'O'),
(25, 'soles', 'O'),
(26, 'Australian dollars', 'O'),
(27, 'dollar australian', 'O'),
(28, 'Dollars Australiens', 'O'),
(29, 'czk', 'O'),
(30, 'franc guinéen', 'O'),
(31, 'Dollars Canadien', 'O'),
(32, 'francs', 'O'),
(33, 'PLN', 'O'),
(34, 'pounds', 'O'),
(35, 'DZD', 'O'),
(36, 'TL', 'O'),
(37, 'Canadian dollar', 'O'),
(38, 'roubles', 'O'),
(39, 'Dollar canadien', 'O'),
(40, 'GBP', 'O'),
(41, 'pesos argentins', 'O'),
(42, 'Suisse franc', 'O'),
(43, 'YUAN', 'O'),
(44, '660.835', 'O'),
(45, 'suisse', 'O'),
(46, 'CNY', 'O'),
(47, 'pound', 'O'),
(48, 'pesos mexicains', 'O'),
(49, 'RINGGINT', 'O'),
(50, '$ canadien ', 'O'),
(51, 'dollars singapouriens', 'O'),
(52, 'Can ', 'O'),
(53, 'Dinars', 'O'),
(54, 'Lira', 'O'),
(55, 'Dollar Singapourien', 'O'),
(56, 'MXN pesos', 'O'),
(57, 'pesos mexicain', 'O'),
(58, '420', 'O'),
(59, 'ARS', 'O'),
(60, 'Hryvnia', 'O'),
(61, '$CAD', 'O'),
(62, 'VND', 'O'),
(63, 'FR SUISSE', 'O'),
(64, 'Dinar tunisien ', 'O'),
(65, 'GBP (livre sterling)', 'O'),
(66, '$ ', 'O'),
(67, 'Fcfa', 'O'),
(68, 'KZT', 'O'),
(69, 'Livre £', 'O'),
(70, 'TRY', 'O'),
(71, 'Dirham ', 'O'),
(72, 'MAD', 'O'),
(73, 'pesos', 'O'),
(74, 'Chinese yuan', 'O'),
(75, 'F CFA', 'O'),
(76, 'lei', 'O'),
(77, 'US Dollar', 'O'),
(78, 'Dinar', 'O'),
(79, 'Francs Suisses', 'O'),
(80, 'couronnes norvégiennes', 'O'),
(81, 'quetzal', 'O'),
(82, '$ CDN', 'O'),
(83, 'Ch', 'O'),
(84, 'Sol', 'O'),
(85, 'NOK', 'O'),
(86, 'SGP', 'O'),
(87, 'AED', 'O'),
(88, 'forint', 'O'),
(89, '$ CAD', 'O'),
(90, 'tengue', 'O'),
(91, 'Franc CFA', 'O'),
(92, 'BRL', 'O'),
(93, 'Roupie ', 'O'),
(94, 'RM', 'O'),
(95, 'dollar us', 'O'),
(96, 'Dollar CAD', 'O'),
(97, 'Dinar Algérien ', 'O'),
(98, 'KRW', 'O'),
(99, '$COP', 'O'),
(100, '$AUD', 'O'),
(101, 'CAN$', 'O'),
(102, 'canadienne', 'O'),
(103, 'FRANCS CFA', 'O'),
(104, 'XOF ', 'O'),
(105, 'UAN', 'O'),
(106, 'UAH', 'O'),
(107, '$CAN', 'O'),
(108, 'Ouguiyas', 'O'),
(109, 'Yuan chinois', 'O'),
(110, 'Livre égyptienne', 'O'),
(111, 'Yuans', 'O'),
(112, 'LKR', 'O'),
(113, 'CAD$', 'O'),
(114, 'Ringgit', 'O'),
(115, 'FRANC', 'O'),
(116, 'DT', 'O'),
(117, 'Livre égyptien', 'O'),
(118, 'Livres égyptiens', 'O'),
(119, 'Dirham marocain', 'O'),
(120, 'Dollar néo-zélandais', 'O');
