INSERT INTO ParamMail (code, libelle, exemple) VALUES
('convention.numero', 'Numéro de la convention', '25869'),
('convention.typeStage', 'Type de stage de la convention', 'Formation Initiale - Stage Obligatoire'),
('convention.paysAccueil', 'Pays d''accueil de la convention', 'FRANCE'),
('convention.etape', 'Étape de la convention', 'M5I294 - Master Management et organisations - Parcours Management dans les pays du sud'),
('convention.sujet', 'sujet du stage', NULL),
('convention.fonction', 'Fonctions et tâches (missions et compétences)', NULL),
('convention.dateDebut', 'Date début du stage', '01/08/2021'),
('convention.dateFin', 'Date fin du stage', '31/08/2021'),
('convention.tempsTravail', 'Type du temps de travail', 'Temps plein'),
('convention.tempsTravailComment', 'Commentaire sur le type du temps de travail', NULL),
('convention.lien', 'Lien de l''application pointant sur la convention', 'http://urldexemple.domain.org/convention/numero'),
('tuteurPro.nom', 'Nom du tuteur professionnel', NULL),
('tuteurPro.prenom', 'Prénom du tuteur professionnel', NULL),
('tuteurPro.mail', 'Adresse mail du tuteur professionnel', NULL),
('tuteurPro.tel', 'Numéro de téléphone du tuteur professionnel', NULL),
('tuteurPro.etabAccueil', 'Établissement d''accueil du tuteur professionnel', NULL),
('tuteurPro.serviceAccueil', 'Service d''accueil du tuteur professionnel', NULL),
('tuteurPro.fonction', 'Fonction du tuteur professionnel', NULL),
('signataire.nom', 'Nom du signataire', NULL),
('signataire.prenom', 'Prénom du signataire', NULL),
('signataire.mail', 'Adresse mail du signataire', NULL),
('signataire.tel', 'Numéro de téléphone du signataire', NULL),
('signataire.fonction', 'Fonction du signataire', NULL),
('etudiant.nom', 'Nom de l''étudiant', NULL),
('etudiant.prenom', 'Prénom de l''étudiant', NULL),
('etudiant.mail', 'Adresse mail de l''étudiant', NULL),
('etudiant.tel', 'Numéro de téléphone de l''étudiant', NULL),
('avenant.numero', 'Numéro de l''avenant', NULL),
('modifiePar.nom', 'Nom de l''utilisateur ayant modifié/validé', NULL),
('modifiePar.prenom', 'Prénom de l''utilisateur ayant modifié/validé', NULL);
