INSERT INTO ParamConvention (code, libelle, exemple) VALUES
('centreGestion.prenomViseur', 'Prénom du viseur', 'T'),
('centreGestion.mail', 'Mail du centre', ''),
('centreGestion.nomCentre', 'Nom du centre', 'ETABLISSEMENT DANIELLE'),
('centreGestion.nomViseur', 'Nom du viseur', 'T'),
('centreGestion.codeUniversite', 'Code Université', 'UR1'),
('centreGestion.telephone', 'Téléphone', '0223232323'),
('centreGestion.voie', 'Voie', '34'),
('centreGestion.commune', 'Commune', 'rennes'),
('centreGestion.codePostal', 'Code postal', '35000'),
('centreGestion.adresse', 'Bâtiment / Résidence / Z.I.', 'rue du general de gaulle'),
('convention.nomSignataireComposante', 'Nom du signataire ', 'Jacques MIRIEL'),
('etudiant.identEtudiant', 'Identifiant Etudiant', '11002426'),
('etudiant.dateNais', 'Date de naissance de l''étudiant', '08/07/1998'),
('etudiant.numEtudiant', 'Numéro Etudiant', '11002426'),
('etudiant.codeSexe', 'Code sexe de l''étudiant', 'M'),
('etudiant.numSS', 'Numéro de Sécurité Sociale de l''étudiant', '188074419003876'),
('etudiant.mail', 'Mail de l''étudiant', 'salim.amiour@etudiant.univ-rennes1.fr'),
('etudiant.nom', 'Nom de l''étudiant', 'AMIOUR'),
('etudiant.prenom', 'Prénom de l''étudiant', 'SALIM'),
('convention.libelleCPAM', 'Libellé CPAM', 'CPAM d''Ille et Vilaine'),
('convention.paysEtudiant', 'Pays étudiant', 'FRANCE'),
('convention.montantGratification', 'Montant Gratification', '450.00'),
('convention.dateFinStage', 'Date de fin de stage', '20/05/2011'),
('convention.codeCaisse', 'Code Caisse', 'CPAM'),
('convention.villeEtudiant', 'Ville Etudiant', 'SAINT-NAZAIRE'),
('convention.ufrLibelle', 'Libellé UFR', 'IUT de Rennes'),
('convention.details', 'Détails de la convention', 'calcul des paies'),
('convention.travailNuitFerie', 'Travail nuit férié', 'travail un dimanche par mois'),
('convention.annee', 'Année', '2010/2011'),
('contact.fonction', 'Fonction', 'rh 5'),
('contact.civiliteLibelle', 'Civilité', 'Mme'),
('contact.tel', 'Tel', '0223232323'),
('contact.mail', 'Mail', 'danielle.martineau@univ-renens1.fr'),
('contact.nom', 'Nom contact', 'MARTIN CINQ'),
('contact.prenom', 'Prénom', 'Dany'),
('convention.uniteGratificationLibelle', 'Unité gratification', 'net'),
('convention.telPortableEtudiant', 'Téléphone portable de l''étudiant', '0674479409'),
('convention.etapeLibelle', 'Libellé étape', 'Licence professionnelle chargé d''affaire en génie climatique'),
('convention.creditECTS', 'Crédit ECTS', '10.00'),
('convention.sujetStage', 'Sujet stage', 'sujet du stage'),
('convention.libelleFinalite', 'Libellé finalité', ''),
('convention.avantagesNature', 'Avantages nature', 'restaurant entreprise'),
('convention.interruptionStage', 'Interruption stage', 'Oui'),
('convention.qualiteSignataire', 'Qualité du signataire', 'Le Directeur de l''IUT'),
('convention.tempsTravailLibelle', 'Temps travail', 'Temps Complet'),
('convention.dureeExceptionnelle', 'Durée exceptionnelle', '5'),
('convention.codeDepartement', 'Code département', '922'),
('convention.dateDebutStage', 'Date de début de stage', '03/01/2011'),
('convention.commentaireDureeTravail', 'Commentaire durée travail', 'travail en groupe'),
('convention.courrielPersoEtudiant', 'Courriel personnel étudiant', 'michelle.montoir@laposte.net'),
('convention.themeLibelle', 'Thème', 'Administration publique'),
('convention.modeValidationStageLibelle', 'Mode de validation du stage', 'Evaluation du mémoire et soutenance'),
('convention.nbJoursHebdo', 'Nombre de jours hebdomadaire', '4'),
('convention.origineStageLibelle', 'Origine du stage', 'candidature spontanée'),
('convention.insee', 'INSEE', '188074419003876'),
('structure.activitePrincipale', 'Activité principale de l''établissement d''accueil', 'informatique'),
('structure.raisonSociale', 'Raison sociale de l''établissement d''accueil', 'DANIELLE TIERS'),
('structure.mail', 'Mail de l''établissement d''accueil', ''),
('structure.numeroSiret', 'Numéro de Siret de l''établissement d''accueil', ''),
('structure.effectifLibelle', 'Effectif de l''établissement d''accueil', '10 à 49'),
('structure.typeStructureLibelle', 'Type de l''établissement d''accueil', 'Entreprise privée'),
('structure.telephone', 'Téléphone', '0223232323'),
('structure.statutJuridiqueLibelle', 'Statut juridique', 'SARL'),
('structure.voie', 'Voie', 'Rue des vignes'),
('structure.commune', 'Commune', 'XXXX'),
('structure.codePostal', 'Code postal', '563333'),
('structure.paysLibelle', 'Pays de l''établissement d''accueil', 'FINLANDE'),
('convention.nomEtabRef', 'Nom de l''établissement de référence', 'UNIVERSITE DE RENNES 1'),
('convention.dureeStage', 'Durée du stage', '17'),
('convention.codeCursusLMD', 'Code cursus LMD', 'L'),
('convention.modeVersGratificationLibelle', 'Mode de versement de la gratification', 'Virement bancaire'),
('convention.adresseEtabRef', 'Adresse de l''établissement de référence', '2 RUE DU THABOR CS 46510 35065 Rennes'),
('convention.natureTravailLibelle', 'Nature travail', 'Rapport de stage + Projet professionnel'),
('convention.codePostalEtudiant', 'Code postal de l''étudiant', '44600'),
('convention.adresseEtudiant', 'Adresse de l''étudiant', '30 rue claude bernard'),
('convention.assuranceLibelle', 'Assurance', 'en qualité d''ayant droit d''assuré social'),
('convention.fonctionsEtTaches', 'Fonctions et taches', 'gestion de la comptabilité'),
('convention.modeEncadreSuivi', 'Mode d''encadrement et de suivi', 'rdv téléphonique le vendredi'),
('convention.nbHeuresHebdo', 'Nombre d''heures hebdomadaire', '35.00'),
('signataire.fonction', 'Fonction du signataire', 'compta'),
('signataire.civiliteLibelle', 'Civilité du signataire', 'M.'),
('signataire.tel', 'Téléphone du signataire', '0223232312'),
('signataire.mail', 'Mail du signataire', 'martin.jules@free.fr'),
('signataire.nom', 'Nom du signataire', 'MARTIN'),
('signataire.prenom', 'Prénom du signataire', 'Jules cinq'),
('convention.telEtudiant', 'Téléphone de l''étudiant', '0240706665'),
('enseignant.bureau', 'Bureau de l''enseignant', '312'),
('enseignant.affectationLibelle', 'Affectation de l''enseignant', 'Faculté de droit et science politique'),
('enseignant.tel', 'Téléphone de l''enseignant', '+33 2 23 23 30 28'),
('enseignant.nom', 'Nom de l''enseignant', 'Martin'),
('enseignant.prenom', 'Prénom de l''enseignant', 'Jean-Paul'),
('service.nom', 'Nom du service d''accueil', 'RH CINQ'),
('service.voie', 'Voie du service d''accueil', '35 rue du ciel'),
('service.commune', 'Commune du service d''accueil', 'REKIAVIK'),
('service.codePostal', 'Code postal du service d''accueil', '25000'),
('service.paysLibelle', 'Pays du service d''accueil', 'FINLANDE'),
('avenant.sujetStage', 'Sujet stage Avenant', 'nouveau sujet'),
('avenant.motifAvenant', 'Motif de l''avenant', 'test nouvel avenant'),
('avenant.id', 'Numéro Avenant', '17612'),
('convention.id', 'Numéro de convention', '36015'),
('avenant.dateDebutStage', 'Date de début de stage Avenant', '20/05/2011'),
('avenant.dateFinStage', 'Date de fin de stage Avenant', '20/05/2011'),
('enseignant.mail', 'Mail de l''enseignant', 'martin.jules@free.fr'),
('convention.volumeHoraireFormation', 'Nombre d''heures total du stage', '924'),
('centreGestion.prenomPresidentEtab', 'Prénom du président de l\'établissement', 'Pierre'),
('centreGestion.nomPresidentEtab', 'Nom du président de l\'établissement', 'Martin'),
('centreGestion.qualitePresidentEtab', 'Qualité du président de l\'établissement', 'Le Directeur de l\'université'),
('convention.dureeStageHeurePeriode', 'Durée effective du stage en mois/jour/heures', 'X mois Y jour(s) et Z heure(s)'),
('centreGestion.qualiteViseur', 'Qualité du viseur', 'Le Directeur de l\'université'),
('convention.competences', 'Compétences', 'Connaissances, capacités etc'),
('convention.deviseGratification', 'Devise de la gratification', 'euros'),
('avenant.motifs', 'Liste des motifs de l\'avenant', 'Sous forme de tableau avec en titre la raison, à droites les anciennes valeurs et à gauche les nouvelles'),
('convention.periodesInterruptions', 'Liste des périodes d\'interruptions de stage', '$LIST convention.periodesInterruptions as periode $FI du ${periode.dateDebutInterruption}\nau ${periode.dateFinInterruption} $ENDLIST'),
('convention.nbConges', 'Nombre de jours de congés autorisés', '1 jour par mois'),
('convention.uniteDureeGratificationLibelle', 'Fréquence de versement de la gratification', 'mois'),
('service.batiment', 'Bâtiment / Résidence / Z.I', 'Bat. 1'),
('structure.batiment', 'Bâtiment / Résidence / Z.I', 'Bat. 1'),
('convention.regionCPAM', 'Région CPAM', 'Bretagne'),
('convention.adresseCPAM', 'Adresse CPAM', 'BP 20321 56021 Vannes Cedex');
