INSERT INTO TemplateMail (code, libelle, objet, texte, dateCreation, loginCreation)VALUES
('ETU_CREA_CONVENTION', 'Création d''une convention par l''étudiant', 'Création d''une convention', 'Texte à modifier', NOW(), 'liquibase'),
('ETU_MODIF_CONVENTION', 'Modification d''une convention par l''étudiant', 'Modification d''une convention', 'Texte à modifier', NOW(), 'liquibase'),
('GES_CREA_CONVENTION', 'Création d''une convention par le gestinnaire', 'Création d''une convention', 'Texte à modifier', NOW(), 'liquibase'),
('GES_MODIF_CONVENTION', 'Modification d''une convention par le gestionnaire', 'Modification d''une convention', 'Texte à modifier', NOW(), 'liquibase'),
('ETU_CREA_AVENANT', 'Création d''un avenant par l''étudiant', 'Création d''un avenant', 'Texte à modifier', NOW(), 'liquibase'),
('ETU_MODIF_AVENANT', 'Modification d''un avenant par l''étudiant', 'Modification d''un avenant', 'Texte à modifier', NOW(), 'liquibase'),
('GES_CREA_AVENANT', 'Création d''un avenant par le gestinnaire', 'Création d''un avenant', 'Texte à modifier', NOW(), 'liquibase'),
('GES_MODIF_AVENANT', 'Modification d''un avenant par le gestionnaire', 'Modification d''un avenant', 'Texte à modifier', NOW(), 'liquibase'),
('CONVENTION_VALID_PEDAGOGIQUE', 'Validation pédagogique d''une convention', 'Convention validée pédogogiquement', 'Texte à modifier', NOW(), 'liquibase'),
('CONVENTION_VALID_ADMINISTRATIVE', 'Validation administrative d''une convention', 'Convention validée administrativement', 'Texte à modifier', NOW(), 'liquibase'),
('AVENANT_VALIDATION', 'Validation d''un avenant', 'Avenant validé', 'Texte à modifier', NOW(), 'liquibase'),
('CONVENTION_DEVALID_ADMINISTRATIVE', 'Dévalidation administrative d''une convention', 'Dévalidation d''une convention', 'Texte à modifier', NOW(), 'liquibase'),
('CONVENTION_DEVALID_PEDAGOGIQUE', 'Dévalidation pédagogique d''une convention', 'Dévalidation d''une convention', 'Texte à modifier', NOW(), 'liquibase'),
('CONVENTION_VERIF_ADMINISTRATIVE', 'Vérification administrative d''une convention', 'Vérification d''une convention', 'Texte à modifier', NOW(), 'liquibase'),
('CONVENTION_DEVERIF_ADMINISTRATIVE', 'Annulation de la vérification administrative d''une convention', 'Vérification annulée d''une convention', 'Texte à modifier', NOW(), 'liquibase'),
('FICHE_EVAL_ETU', 'Prévenir l\'étudiant qu\'il peut remplir sa fiche', 'Votre fiche d\'évaluation de stage est disponible', 'Texte à modifier', NOW(), 'liquibase'),
('FICHE_EVAL_ENSEIGNANT', 'Prévenir l\'enseignant qu\'il peut remplir sa fiche', 'Votre fiche d\'évaluation de stage est disponible', 'Texte à modifier', NOW(), 'liquibase'),
('FICHE_EVAL_TUTEUR', 'Prévenir le tuteur professionel qu\'il peut remplir sa fiche', 'Votre fiche d\'évaluation de stage est disponible', 'Texte à modifier', NOW(), 'liquibase'),
('RAPPEL_FICHE_EVAL_ETU', 'Rappeler à l\'étudiant qu\'il peut remplir sa fiche', 'Votre fiche d\'évaluation de stage est disponible', 'Texte à modifier', NOW(), 'liquibase'),
('RAPPEL_FICHE_EVAL_ENSEIGNANT', 'Rappeler à l\'enseignant qu\'il peut remplir sa fiche', 'Votre fiche d\'évaluation de stage est disponible', 'Texte à modifier', NOW(), 'liquibase'),
('RAPPEL_FICHE_EVAL_TUTEUR', 'Rappeler au tuteur professionel qu\'il peut remplir sa fiche', 'Votre fiche d\'évaluation de stage est disponible', 'Texte à modifier', NOW(), 'liquibase');