INSERT INTO `CPAM` VALUES (1,'Ile-de-France','Caisse primaire d\'assurance maladie (CPAM) de Paris','75948 Paris Cedex 19');
INSERT INTO `CPAM` VALUES (2,'Ile-de-France','Caisse primaire d\'assurance maladie (CPAM) de la Seine-et-Marne','77605 Marne-la-Vallée Cedex 3');
INSERT INTO `CPAM` VALUES (3,'Ile-de-France','Caisse primaire d\'assurance maladie (CPAM) des Yvelines','78085 Yvelines Cedex 9');
INSERT INTO `CPAM` VALUES (4,'Ile-de-France','Caisse primaire d\'assurance maladie (CPAM) de l\'Essonne','91040 Évry Cedex');
INSERT INTO `CPAM` VALUES (5,'Ile-de-France','Caisse primaire d\'assurance maladie (CPAM) des Hauts-de-Seine','92026 Nanterre Cedex');
INSERT INTO `CPAM` VALUES (6,'Ile-de-France','Caisse primaire d\'assurance maladie (CPAM) de Seine-Saint-Denis','CS 60300 93018 Bobigny Cedex');
INSERT INTO `CPAM` VALUES (7,'Ile-de-France','Caisse primaire d\'assurance maladie (CPAM) du Val-d\'Oise','95017 Cergy-Pontoise Cedex');
INSERT INTO `CPAM` VALUES (8,'Ile-de-France','Caisse primaire d\'assurance maladie (CPAM) du Val-de-Marne','94031 Créteil Cedex');
INSERT INTO `CPAM` VALUES (9,'Auvergne-Rhône-Alpes','Caisse primaire d\'assurance maladie (CPAM) d\'Ardèche','6 avenue de l\'Europe-Unie 07000 Privas');
INSERT INTO `CPAM` VALUES (10,'Auvergne-Rhône-Alpes','Caisse primaire d\'assurance maladie (CPAM) du Cantal','15 rue Pierre-Marty 15010 Aurillac Cedex');
INSERT INTO `CPAM` VALUES (11,'Auvergne-Rhône-Alpes','Caisse primaire d\'assurance maladie (CPAM) de Haute-Loire','10 avenue André-Soulier CS 70324 43009 Le Puy-en-Velay Cedex');
INSERT INTO `CPAM` VALUES (12,'Auvergne-Rhône-Alpes','Caisse primaire d\'assurance maladie (CPAM) de Haute-Savoie','2 rue Robert-Schuman 74984 Annecy Cedex 9');
INSERT INTO `CPAM` VALUES (13,'Auvergne-Rhône-Alpes','Caisse primaire d\'assurance maladie (CPAM) de l\'Ain','1 place de la Grenouillère 01015 Bourg-en-Bresse Cedex');
INSERT INTO `CPAM` VALUES (14,'Auvergne-Rhône-Alpes','Caisse primaire d\'assurance maladie (CPAM) de l\'Allier','9-11 rue Achille-Roche 03010 Moulins Cedex');
INSERT INTO `CPAM` VALUES (15,'Auvergne-Rhône-Alpes','Caisse primaire d\'assurance maladie (CPAM) de l\'Isère','38045 Grenoble Cedex 9');
INSERT INTO `CPAM` VALUES (16,'Auvergne-Rhône-Alpes','Caisse primaire d\'assurance maladie (CPAM) de la Drôme','6 avenue Édouard-Herriot 26024 Valence Cedex');
INSERT INTO `CPAM` VALUES (17,'Auvergne-Rhône-Alpes','Caisse primaire d\'assurance maladie (CPAM) de la Loire','CS 72701 42027 Saint-Étienne Cedex 1');
INSERT INTO `CPAM` VALUES (18,'Auvergne-Rhône-Alpes','Caisse primaire d\'assurance maladie (CPAM) du Puy-de-Dôme','63031 Clermont-Ferrand Cedex 9');
INSERT INTO `CPAM` VALUES (19,'Auvergne-Rhône-Alpes','Caisse primaire d\'assurance maladie (CPAM) du Rhône','69907 Lyon Cedex 20');
INSERT INTO `CPAM` VALUES (20,'Auvergne-Rhône-Alpes','Caisse primaire d\'assurance maladie (CPAM) de Savoie','5 avenue Jean-Jaurès CS 40015 73015 Chambéry Cedex');
INSERT INTO `CPAM` VALUES (21,'Bourgogne-Franche-Comté','Caisse primaire d\'assurance maladie (CPAM) de Côte-d\'Or','CS 34548 21045 Dijon Cedex');
INSERT INTO `CPAM` VALUES (22,'Bourgogne-Franche-Comté','Caisse primaire d\'assurance maladie (CPAM) du Doubs','25036 Besançon Cedex');
INSERT INTO `CPAM` VALUES (23,'Bourgogne-Franche-Comté','Caisse primaire d\'assurance maladie (CPAM) de Haute-Saône','9 boulevard des Alliés BP 439 70020 Vesoul Cedex');
INSERT INTO `CPAM` VALUES (24,'Bourgogne-Franche-Comté','Caisse primaire d\'assurance maladie (CPAM) du Jura','8 rue des Lilas 39031 Lons-le-Saunier Cedex');
INSERT INTO `CPAM` VALUES (25,'Bourgogne-Franche-Comté','Caisse primaire d\'assurance maladie (CPAM) de l\'Yonne','1-3 rue du Moulin 89024 Auxerre Cedex');
INSERT INTO `CPAM` VALUES (26,'Bourgogne-Franche-Comté','Caisse primaire d\'assurance maladie (CPAM) de la Nièvre','58025 Nevers Cedex');
INSERT INTO `CPAM` VALUES (27,'Bourgogne-Franche-Comté','Caisse primaire d\'assurance maladie (CPAM) de Saône-et-Loire','71022 Mâcon Cedex 9');
INSERT INTO `CPAM` VALUES (28,'Bourgogne-Franche-Comté','Caisse primaire d\'assurance maladie (CPAM) du Territoire de Belfort','12 rue du Général-Strolz 90021 Belfort Cedex');
INSERT INTO `CPAM` VALUES (29,'Bretagne','Caisse primaire d\'assurance maladie (CPAM) des Côtes-d\'Armor','22024 Saint-Brieuc Cedex 1');
INSERT INTO `CPAM` VALUES (30,'Bretagne','Caisse primaire d\'assurance maladie (CPAM) du Finistère','1 rue de Savoie 29282 Brest Cedex');
INSERT INTO `CPAM` VALUES (31,'Bretagne','Caisse primaire d\'assurance maladie (CPAM) d\'Ille-et-Vilaine','35024 Rennes Cedex 9');
INSERT INTO `CPAM` VALUES (32,'Bretagne','Caisse primaire d\'assurance maladie (CPAM) du Morbihan','BP 20321 56021 Vannes Cedex');
INSERT INTO `CPAM` VALUES (33,'Centre-Val de Loire','Caisse primaire d\'assurance maladie (CPAM) du Cher','21 boulevard de la République 18030 Bourges Cedex 9');
INSERT INTO `CPAM` VALUES (34,'Centre-Val de Loire','Caisse primaire d\'assurance maladie (CPAM) d\'Eure-et-Loir','11 rue du Docteur-André-Haye 28034 Chartres Cedex');
INSERT INTO `CPAM` VALUES (35,'Centre-Val de Loire','Caisse primaire d\'assurance maladie (CPAM) d\'Indre-et-Loire','36 rue Édouard-Vaillant 37035 Tours Cedex 9');
INSERT INTO `CPAM` VALUES (36,'Centre-Val de Loire','Caisse primaire d\'assurance maladie (CPAM) de l\'Indre','14 rue Claude-Nicolas-Ledoux 36026 Châteauroux Cedex');
INSERT INTO `CPAM` VALUES (37,'Centre-Val de Loire','Caisse primaire d\'assurance maladie (CPAM) du Loiret','45021 Orléans Cedex 1');
INSERT INTO `CPAM` VALUES (38,'Centre-Val de Loire','Caisse primaire d\'assurance maladie (CPAM) du Loir-et-Cher','6 rue Louis-Armand 41022 Blois Cedex');
INSERT INTO `CPAM` VALUES (39,'Corse','Caisse primaire d\'assurance maladie (CPAM) de Corse-du-Sud','20702 Ajaccio Cedex 9');
INSERT INTO `CPAM` VALUES (40,'Corse','Caisse primaire d\'assurance maladie (CPAM) de Haute-Corse','5 avenue Jean-Zuccarelli 20406 Bastia Cedex 9');
INSERT INTO `CPAM` VALUES (41,'France d\'Outre-mer','Caisse générale de sécurité sociale (CGSS) de La Réunion','4 boulevard Doret CS 53001 97741 Saint-Denis Cedex 9');
INSERT INTO `CPAM` VALUES (42,'France d\'Outre-mer','Caisse générale de sécurité sociale (CGSS) de Martinique','Four-à-Chaux ZAC de Manhity 97282 Le Lamentin');
INSERT INTO `CPAM` VALUES (43,'France d\'Outre-mer','Caisse générale de sécurité sociale (CGSS) de Guadeloupe','Rue Boisripeaux 97139 Les Abymes');
INSERT INTO `CPAM` VALUES (44,'France d\'Outre-mer','Caisse générale de sécurité sociale (CGSS) de Guyane','Espace Turenne-Radamonthe Route de Raban 97300 Cayenne Cedex');
INSERT INTO `CPAM` VALUES (45,'Grand Est','Caisse primaire d\'assurance maladie (CPAM) des Ardennes','14 avenue Georges-Corneau CS 30101 08101 Charleville-Mézières Cedex');
INSERT INTO `CPAM` VALUES (46,'Grand Est','Caisse primaire d\'assurance maladie (CPAM) du Bas-Rhin','16 rue de Lausanne 67090 Strasbourg Cedex');
INSERT INTO `CPAM` VALUES (47,'Grand Est','Caisse primaire d\'assurance maladie (CPAM) de Haute-Marne','18 boulevard du Maréchal-de-Lattre-de-Tassigny CS 22028 52915 Chaumont Cedex 9');
INSERT INTO `CPAM` VALUES (48,'Grand Est','Caisse primaire d\'assurance maladie (CPAM) du Haut-Rhin','19 boulevard du Champs-de-Mars BP 40454 68022 Colmar Cedex');
INSERT INTO `CPAM` VALUES (49,'Grand Est','Caisse primaire d\'assurance maladie (CPAM) de l\'Aube','113 rue Étienne-Pédron CS 90500 10030 Troyes Cedex');
INSERT INTO `CPAM` VALUES (50,'Grand Est','Caisse primaire d\'assurance maladie (CPAM) de la Marne','4 rue du Ruisselet CS 30001 51086 Reims Cedex');
INSERT INTO `CPAM` VALUES (51,'Grand Est','Caisse primaire d\'assurance maladie (CPAM) de la Meuse','1 rue de Polval CS 50907 55015 Bar-le-Duc Cedex');
INSERT INTO `CPAM` VALUES (52,'Grand Est','Caisse primaire d\'assurance maladie (CPAM) de Moselle','CS 80001 57751 Metz Cedex 9');
INSERT INTO `CPAM` VALUES (53,'Grand Est','Caisse primaire d\'assurance maladie (CPAM) des Vosges','CS 30584 88015 Épinal Cedex');
INSERT INTO `CPAM` VALUES (54,'Hauts-de-France','Caisse primaire d\'assurance maladie (CPAM) de Fives','2 rue d\'Iéna BP 01 59000 Lille Cedex 9');
INSERT INTO `CPAM` VALUES (55,'Hauts-de-France','Caisse primaire d\'assurance maladie (CPAM) de Flandres-Dunkerque-Armentières','2 rue de la Batellerie CS 94523 59386 Dunkerque Cedex 1');
INSERT INTO `CPAM` VALUES (56,'Hauts-de-France','Caisse primaire d\'assurance maladie (CPAM) du Hainaut','63 rue du Rempart CS 60499 59321 Valenciennes Cedex');
INSERT INTO `CPAM` VALUES (57,'Hauts-de-France','Caisse primaire d\'assurance maladie (CPAM) de l\'Aisne','29 boulevard Roosevelt CS 20606 02323 Saint-Quentin Cedex');
INSERT INTO `CPAM` VALUES (58,'Hauts-de-France','Caisse primaire d\'assurance maladie (CPAM) de l\'Artois','11 boulevard du Président-Allende CS 90014 62014 Arras Cedex');
INSERT INTO `CPAM` VALUES (59,'Hauts-de-France','Caisse primaire d\'assurance maladie (CPAM) de l\'Oise','1 rue de Savoie BP 30326 60013 Beauvais Cedex');
INSERT INTO `CPAM` VALUES (60,'Hauts-de-France','Caisse primaire d\'assurance maladie (CPAM) de la Côte d\'Opale','35 rue Descartes CS 90001 62108 Calais Cedex');
INSERT INTO `CPAM` VALUES (61,'Hauts-de-France','Caisse primaire d\'assurance maladie (CPAM) de la Somme','8 place Louis-Sellier 80021 Amiens Cedex 1');
INSERT INTO `CPAM` VALUES (62,'Hauts-de-France','Caisse primaire d\'assurance maladie (CPAM) de Lille-Douai','125 rue Saint-Sulpice CS 20821 59508 Douai Cedex');
INSERT INTO `CPAM` VALUES (63,'Hauts-de-France','Caisse primaire d\'assurance maladie (CPAM) de Roubaix-Tourcoing','2 place Sébastopol CS 40700 59208 Tourcoing Cedex');
INSERT INTO `CPAM` VALUES (64,'Normandie','Caisse primaire d\'assurance maladie (CPAM) du Calvados','108 boulevard Jean-Moulin CS 10001 14031 Caen Cedex 9');
INSERT INTO `CPAM` VALUES (65,'Normandie','Caisse primaire d\'assurance maladie (CPAM) de l\'Eure','27030 Évreux Cedex');
INSERT INTO `CPAM` VALUES (66,'Normandie','Caisse primaire d\'assurance maladie (CPAM) de la Manche','CS 51212 50012 Saint-Lô Cedex');
INSERT INTO `CPAM` VALUES (67,'Normandie','Caisse primaire d\'assurance maladie (CPAM) de l\'Orne','34 place Bonet CS 30020 61012 Alençon Cedex');
INSERT INTO `CPAM` VALUES (68,'Normandie','Caisse primaire d\'assurance maladie (CPAM) de Rouen-Elbeuf-Dieppe','CS 76039 76039 Rouen Cedex 1');
INSERT INTO `CPAM` VALUES (69,'Normandie','Caisse primaire d\'assurance maladie (CPAM) du Havre','CS 80000 76094 Le Havre Cedex');
INSERT INTO `CPAM` VALUES (70,'Nouvelle-Aquitaine','Caisse primaire d\'assurance maladie (CPAM) de Bayonne','68-72 allées Marines CS 98501 64111 Bayonne Cedex');
INSERT INTO `CPAM` VALUES (71,'Nouvelle-Aquitaine','Caisse primaire d\'assurance maladie (CPAM) de Charente','30 boulevard de Bury CS 80000 16910 Angoulême Cedex 9');
INSERT INTO `CPAM` VALUES (72,'Nouvelle-Aquitaine','Caisse primaire d\'assurance maladie (CPAM) de Charente-Maritime','55 rue de Suède CS 70507 17014 La Rochelle Cedex 1');
INSERT INTO `CPAM` VALUES (73,'Nouvelle-Aquitaine','Caisse primaire d\'assurance maladie (CPAM) de Corrèze','6 rue Souham 19033 Tulle Cedex');
INSERT INTO `CPAM` VALUES (74,'Nouvelle-Aquitaine','Caisse primaire d\'assurance maladie (CPAM) de Creuse','Rue Marcel-Brunet BP 109 23000 Guéret');
INSERT INTO `CPAM` VALUES (75,'Nouvelle-Aquitaine','Caisse primaire d\'assurance maladie (CPAM) des Deux-Sèvres','Bessines Parc d\'activités de l\'Ebaupin 1 rue de l\'Angélique 79041 Niort Cedex 9');
INSERT INTO `CPAM` VALUES (76,'Nouvelle-Aquitaine','Caisse primaire d\'assurance maladie (CPAM) de Dordogne','50 rue Claude-Bernard 24010 Périgueux Cedex');
INSERT INTO `CPAM` VALUES (77,'Nouvelle-Aquitaine','Caisse primaire d\'assurance maladie (CPAM) de Gironde','33085 Bordeaux Cedex');
INSERT INTO `CPAM` VALUES (78,'Nouvelle-Aquitaine','Caisse primaire d\'assurance maladie (CPAM) de Haute-Vienne','22 avenue Jean-Gagnant 87037 Limoges Cedex');
INSERT INTO `CPAM` VALUES (79,'Nouvelle-Aquitaine','Caisse primaire d\'assurance maladie (CPAM) des Landes','207 rue de Fontainebleau 40013 Mont-de-Marsan Cedex');
INSERT INTO `CPAM` VALUES (80,'Nouvelle-Aquitaine','Caisse primaire d\'assurance maladie (CPAM) de la Vienne','41 rue du Touffenet 86043 Poitiers Cedex 9');
INSERT INTO `CPAM` VALUES (81,'Nouvelle-Aquitaine','Caisse primaire d\'assurance maladie (CPAM) du Lot-et-Garonne','2 rue Diderot 47914 Agen Cedex 9');
INSERT INTO `CPAM` VALUES (82,'Nouvelle-Aquitaine','Caisse primaire d\'assurance maladie (CPAM) de Pau-Pyrénées','26 bis avenue des Lilas 64022 Pau Cedex 9');
INSERT INTO `CPAM` VALUES (83,'Occitanie','Caisse primaire d\'assurance maladie (CPAM) du Gard','14 rue du Cirque-Romain 30921 Nîmes Cedex 9');
INSERT INTO `CPAM` VALUES (84,'Occitanie','Caisse primaire d\'assurance maladie (CPAM) du Gers','11 rue de Châteaudun 32012 Auch Cedex');
INSERT INTO `CPAM` VALUES (85,'Occitanie','Caisse primaire d\'assurance maladie (CPAM) de Haute-Garonne','31093 Toulouse Cedex 9');
INSERT INTO `CPAM` VALUES (86,'Occitanie','Caisse primaire d\'assurance maladie (CPAM) des Hautes-Pyrénées','8 place au Bois 65021 Tarbes Cedex 9');
INSERT INTO `CPAM` VALUES (87,'Occitanie','Caisse primaire d\'assurance maladie (CPAM) de l\'Ariège','1 avenue de Sibian 09015 Foix Cedex');
INSERT INTO `CPAM` VALUES (88,'Occitanie','Caisse primaire d\'assurance maladie (CPAM) de l\'Aude','2 allée de Bezons 11017 Carcassonne Cedex 9');
INSERT INTO `CPAM` VALUES (89,'Occitanie','Caisse primaire d\'assurance maladie (CPAM) de l\'Aveyron','156 avenue de Bamberg 12020 Rodez Cedex 9');
INSERT INTO `CPAM` VALUES (90,'Occitanie','Caisse primaire d\'assurance maladie (CPAM) de l\'Hérault','29 cours Gambetta 34934 Montpellier Cedex 9');
INSERT INTO `CPAM` VALUES (91,'Occitanie','Caisse primaire d\'assurance maladie (CPAM) du Lot','238 rue Hautesserre 46015 Cahors Cedex 9');
INSERT INTO `CPAM` VALUES (92,'Occitanie','Caisse primaire d\'assurance maladie (CPAM) de Mende BP 26','Quartier des Carmes 48000 Mende');
INSERT INTO `CPAM` VALUES (93,'Occitanie','Caisse primaire d\'assurance maladie (CPAM) des Pyrénées-Orientales','BP 89928 66013 Perpignan Cedex 9');
INSERT INTO `CPAM` VALUES (94,'Occitanie','Caisse primaire d\'assurance maladie (CPAM) du Tarn','81016 Albi Cedex 9');
INSERT INTO `CPAM` VALUES (95,'Occitanie','Caisse primaire d\'assurance maladie (CPAM) du Tarn-et-Garonne','592 boulevard Blaise-Doumerc BP 778 82015 Montauban Cedex');
INSERT INTO `CPAM` VALUES (96,'Pays de la Loire','Caisse primaire d\'assurance maladie (CPAM) de la Sarthe','178 avenue Bollée 72033 Le Mans Cedex 9');
INSERT INTO `CPAM` VALUES (97,'Pays de la Loire','Caisse primaire d\'assurance maladie (CPAM) de Loire-Atlantique','9 rue Gaëtan-Rondeau 44958 Nantes Cedex 9');
INSERT INTO `CPAM` VALUES (98,'Pays de la Loire','Caisse primaire d\'assurance maladie (CPAM) de Maine-et-Loire','32 rue Louis-Gain 49937 Angers Cedex 9');
INSERT INTO `CPAM` VALUES (99,'Pays de la Loire','Caisse primaire d\'assurance maladie (CPAM) de Mayenne','37 boulevard Montmorency 53084 Laval Cedex 9');
INSERT INTO `CPAM` VALUES (100,'Pays de la Loire','Caisse primaire d\'assurance maladie (CPAM) de Vendée','61 rue Alain 85931 La Roche-sur-Yon Cedex 9');
INSERT INTO `CPAM` VALUES (101,'Provence-Alpes-Côte-d\'Azur','Caisse primaire d\'assurance maladie (CPAM) des Alpes-de-Haute-Provence','3 rue Alphonse-Richard 04010 Digne-les-Bains Cedex');
INSERT INTO `CPAM` VALUES (102,'Provence-Alpes-Côte-d\'Azur','Caisse primaire d\'assurance maladie (CPAM) des Alpes-Maritimes','06180 Nice Cedex 2');
INSERT INTO `CPAM` VALUES (103,'Provence-Alpes-Côte-d\'Azur','Caisse primaire d\'assurance maladie (CPAM) des Bouches-du-Rhône','13421 Marseille Cedex 20');
INSERT INTO `CPAM` VALUES (104,'Provence-Alpes-Côte-d\'Azur','Caisse primaire d\'assurance maladie (CPAM) des Hautes-Alpes','10 boulevard Georges-Pompidou 05012 Gap Cedex');
INSERT INTO `CPAM` VALUES (105,'Provence-Alpes-Côte-d\'Azur','Caisse primaire d\'assurance maladie (CPAM) du Var','83082 Toulon Cedex');
INSERT INTO `CPAM` VALUES (106,'Provence-Alpes-Côte-d\'Azur','Caisse primaire d\'assurance maladie (CPAM) du Vaucluse','84043 Avignon Cedex 9');
