INSERT INTO `DureeDiffusion` (`idDureeDiffusion`, `libelleDureeDiffusion`) VALUES (18, '1 An et demi');
INSERT INTO `DureeDiffusion` (`idDureeDiffusion`, `libelleDureeDiffusion`) VALUES (12, '1 An');
INSERT INTO `DureeDiffusion` (`idDureeDiffusion`, `libelleDureeDiffusion`) VALUES (11, '11 Mois');
INSERT INTO `DureeDiffusion` (`idDureeDiffusion`, `libelleDureeDiffusion`) VALUES (10, '10 Mois');
INSERT INTO `DureeDiffusion` (`idDureeDiffusion`, `libelleDureeDiffusion`) VALUES (9, '9 Mois');
INSERT INTO `DureeDiffusion` (`idDureeDiffusion`, `libelleDureeDiffusion`) VALUES (8, '8 Mois');
INSERT INTO `DureeDiffusion` (`idDureeDiffusion`, `libelleDureeDiffusion`) VALUES (7, '7 Mois');
INSERT INTO `DureeDiffusion` (`idDureeDiffusion`, `libelleDureeDiffusion`) VALUES (6, '6 Mois');
INSERT INTO `DureeDiffusion` (`idDureeDiffusion`, `libelleDureeDiffusion`) VALUES (5, '5 Mois');
INSERT INTO `DureeDiffusion` (`idDureeDiffusion`, `libelleDureeDiffusion`) VALUES (4, '4 Mois');
INSERT INTO `DureeDiffusion` (`idDureeDiffusion`, `libelleDureeDiffusion`) VALUES (3, '3 Mois');
INSERT INTO `DureeDiffusion` (`idDureeDiffusion`, `libelleDureeDiffusion`) VALUES (2, '2 Mois');
INSERT INTO `DureeDiffusion` (`idDureeDiffusion`, `libelleDureeDiffusion`) VALUES (1, '1 Mois');
