---

###################################################################
### PREREQUIS                                                ######
###################################################################
# -- OS cible
- name: check.invalid.requirement
  fail: 
    -msg: "playbook for OS='{{ target_os.name }}/{{ target_os.version }}' only -> host with OS='{{ ansible_distribution|lower }}/{{ ansible_distribution_major_version }}'"
  when: not(ansible_distribution|lower==target_os.name and ansible_distribution_major_version|int==target_os.version)
####################################################################

###################################################################
### PREREQUIS                                                ######
###################################################################
- name: webapp.config.deploy
  template: 
    src: "templates/estage.qualif.dauphine.psl.eu_estage.conf.j2"
    dest: "/etc/httpd/conf.d/webapps-available/estage.qualif.dauphine.psl.eu_estage.conf"
    owner: root
    group: root
    mode: 0640
- name: webapp.config.enable
  file:
    src: /etc/httpd/conf.d/webapps-available/estage.qualif.dauphine.psl.eu_estage.conf
    dest: /etc/httpd/conf.d/webapps-enabled/estage.qualif.dauphine.psl.eu_estage.conf
    state: link
- name: webapp.config.test
  command: apachectl configtest
  notify: httpd.restart
###################################################################