name: Publish on Github Pages (main + dev)

on:
  push:
    branches: 
      - main
      - dev 

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Build prod (main)
      - name: Install Antora (prod)
        run: (cd src/docs && npm ci)
      - name: Build prod site
        run: (cd src/docs && npm run prestart)
      - name: Move prod site
        run: |
          mkdir -p site
          mv src/docs/build/site/* site

      # Build dev branch
      - name: Checkout dev branch
        run: |
          git fetch origin dev
          git worktree add dev-branch origin/dev

      - name: Install Antora (dev)
        run: (cd dev-branch/src/docs && npm ci)
      - name: Build dev site
        run: (cd dev-branch/src/docs && npm run prestart)
      - name: Move dev site to /dev
        run: |
          mkdir -p site/dev
          mv dev-branch/src/docs/build/site/* site/dev/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
